TOPLEVEL_LANG ?= verilog
SIM ?= icarus
VERILOG_SOURCES = $(shell pwd)/pri_enc.sv
TOPLEVEL := pri_enc # Verilog or SystemVerilog TOP file module name
MODULE   := pri_enc_tb # Python file name


include $(shell cocotb-config --makefiles)/Makefile.sim