/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "dff.sv:3.1-15.10" *)
module dff(clk, rst, din, dout);
  (* src = "dff.sv:4.16-4.19" *)
  input clk;
  wire clk;
  (* src = "dff.sv:6.16-6.19" *)
  input din;
  wire din;
  (* src = "dff.sv:7.16-7.20" *)
  output dout;
  reg dout;
  (* src = "dff.sv:5.16-5.19" *)
  input rst;
  wire rst;
  (* src = "dff.sv:10.3-13.6" *)
  always @(posedge clk)
    if (rst)
      dout <= 1'h0;
    else
      dout <= din;
endmodule
